// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// Runtime Version:4.0.30319.42000
// 
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Drawing;
using CrystalDecisions.CrystalReports.Engine;
using CrystalDecisions.ReportSource;
using CrystalDecisions.Shared;

namespace pmDHCD
{


    public class DelegateConfirmationMinute : ReportClass
    {

        public DelegateConfirmationMinute() : base()
        {
        }

        public override string ResourceName
        {
            get
            {
                return "Report.DelegateConfirmationMinute.rpt";
            }
            set
            {
                // Do nothing
            }
        }

        public override bool NewGenerator
        {
            get
            {
                return true;
            }
            set
            {
                // Do nothing
            }
        }

        public override string FullResourceName
        {
            get
            {
                return "pmDHCD.Report.DelegateConfirmationMinute.rpt";
            }
            set
            {
                // Do nothing
            }
        }

        [Browsable(false)]
        [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
        public Section Section1
        {
            get
            {
                return ReportDefinition.Sections[0];
            }
        }

        [Browsable(false)]
        [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
        public Section Section2
        {
            get
            {
                return ReportDefinition.Sections[1];
            }
        }

        [Browsable(false)]
        [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
        public Section Section3
        {
            get
            {
                return ReportDefinition.Sections[2];
            }
        }

        [Browsable(false)]
        [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
        public Section Section4
        {
            get
            {
                return ReportDefinition.Sections[3];
            }
        }

        [Browsable(false)]
        [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
        public Section Section5
        {
            get
            {
                return ReportDefinition.Sections[4];
            }
        }
    }
}
